### ISSUE TITLE
Legend can not be changed

### ISSUE THREAD

**Issue by z3tt** [jkaupp/nord#2]
First of all, thanks for this nice collection of very good looking color palettes!

I am at the moment using the "victory_bonds" color map to create a line plot and I want to change the legend appearance (e.g. name, labels) but the changes are not visible. Here is a reproducible example:

``` r
suppressMessages(library(nord))
#> Warning: Paket 'nord' wurde unter R Version 3.4.4 erstellt
suppressMessages(library(tidyverse))
#> Warning: Paket 'tidyverse' wurde unter R Version 3.4.3 erstellt
#> Warning: Paket 'tibble' wurde unter R Version 3.4.3 erstellt
#> Warning: Paket 'tidyr' wurde unter R Version 3.4.3 erstellt

dat <- tibble("a" = rep(c("A", "B", "C"), 10), "b" = runif(30, 0, 1))
dat <- dat %>% group_by(a) %>% mutate(c = 1:n())
ggplot(dat, aes(c, b, color = as.factor(a))) + 
  geom_line() + 
  scale_color_nord("victory_bonds", discrete = T, 
                   name = "Landscape type", breaks = c("A", "B", "C"), 
                   labels = c("setup A", "setup B", "setup C"))
```

![](https://i.imgur.com/7AeyqFQ.png)

Created on 2018-03-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

For the moment, I solved the issue by using the colors but not the functions you provide. Is this a bug or am I doing anything wrong here?

Best, Cédric

**Comment by jkaupp** [comment]
Fixed in latest commit.  Use `devtools::install_github("jkaupp/nord")` to use the development version.
